### ISSUE TITLE
Create a PyPi/pip package for this library

### ISSUE THREAD

**Issue by Nufflee** [mvernacc/proptools#6]
I use proptools quite often but I always have to install it from this repo so is there a pip package I could simply install? I have no idea how pip packages work but there's [another `proptools` package](https://github.com/nejucomo/proptools) ([PyPi](https://pypi.org/project/proptools/)) which doesn't have anything to do with propulsion and GitHub is confused by it (so it says that this package can be installed using `pip install proptools` which is not true).
It would be cool if this can be sorted out somehow.

Thank you so much for creating this library tho, it helps speed up my workflow quite a bit!

**Comment by mvernacc** [comment]
@Nufflee Thanks for pointing this out. The name confusion is unfortunate.

I just published proptools to PyPI here: https://pypi.org/project/proptools-rocket/
You should now be able to install from pypi with:
```bash
 pip install proptools-rocket
```

Or install from source:
```bash
git clone https://github.com/mvernacc/proptools.git
cd proptools
pip install -e .
```

**Comment by Nufflee** [comment]
Awesome! Thank you so much!
